This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./document-msc.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file document-msc.acn....done (272 entries accepted, 0 rejected).
Sorting entries.....done (2468 comparisons).
Generating output file document-msc.acr....done (138 lines written, 0 warnings).
Output written in document-msc.acr.
Transcript written in document-msc.alg.
